// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gorselProgramlamaProje.Data;

#nullable disable

namespace gorselProgramlamaProje.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    partial class UygulamaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("gorselProgramlamaProje.Models.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TamamlandiMi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("gorselProgramlamaProje.Models.GunlukOzet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BasariliGorevSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BasarisizGorevSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToplamPomodoroDakika")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("GunlukOzetler");
                });

            modelBuilder.Entity("gorselProgramlamaProje.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("gorselProgramlamaProje.Models.KullaniciAyar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SureSetiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId")
                        .IsUnique();

                    b.HasIndex("SureSetiId");

                    b.ToTable("KullaniciAyarlari");
                });

            modelBuilder.Entity("gorselProgramlamaProje.Models.PomodoroOturumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SureSetiId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("SureSetiId");

                    b.ToTable("PomodoroOturumlari");
                });

            modelBuilder.Entity("gorselProgramlamaProje.Models.SilinenGorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrijinalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TamamlandiMi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("SilinenGorevler");
                });

            modelBuilder.Entity("gorselProgramlamaProje.Models.SureSeti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CalismaSuresi")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MolaSuresi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("SureSetleri");
                });

            modelBuilder.Entity("gorselProgramlamaProje.Models.Gorev", b =>
                {
                    b.HasOne("gorselProgramlamaProje.Models.Kullanici", "Kullanici")
                        .WithMany("Gorevler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("gorselProgramlamaProje.Models.GunlukOzet", b =>
                {
                    b.HasOne("gorselProgramlamaProje.Models.Kullanici", "Kullanici")
                        .WithMany("Ozetler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("gorselProgramlamaProje.Models.KullaniciAyar", b =>
                {
                    b.HasOne("gorselProgramlamaProje.Models.Kullanici", "Kullanici")
                        .WithOne("Ayar")
                        .HasForeignKey("gorselProgramlamaProje.Models.KullaniciAyar", "KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gorselProgramlamaProje.Models.SureSeti", "SureSeti")
                        .WithMany()
                        .HasForeignKey("SureSetiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("SureSeti");
                });

            modelBuilder.Entity("gorselProgramlamaProje.Models.PomodoroOturumu", b =>
                {
                    b.HasOne("gorselProgramlamaProje.Models.Kullanici", "Kullanici")
                        .WithMany("Oturumlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gorselProgramlamaProje.Models.SureSeti", "SureSeti")
                        .WithMany()
                        .HasForeignKey("SureSetiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("SureSeti");
                });

            modelBuilder.Entity("gorselProgramlamaProje.Models.SilinenGorev", b =>
                {
                    b.HasOne("gorselProgramlamaProje.Models.Kullanici", "Kullanici")
                        .WithMany("SilinenGorevler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("gorselProgramlamaProje.Models.SureSeti", b =>
                {
                    b.HasOne("gorselProgramlamaProje.Models.Kullanici", "Kullanici")
                        .WithMany("OlusturduguSureSetleri")
                        .HasForeignKey("KullaniciId");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("gorselProgramlamaProje.Models.Kullanici", b =>
                {
                    b.Navigation("Ayar");

                    b.Navigation("Gorevler");

                    b.Navigation("OlusturduguSureSetleri");

                    b.Navigation("Oturumlar");

                    b.Navigation("Ozetler");

                    b.Navigation("SilinenGorevler");
                });
#pragma warning restore 612, 618
        }
    }
}
